spring:
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate.hbm2ddl-auto: update
      hibernate.connection.charSet: UTF-8
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/geosatis
    username: postgres
    password: postgres
  flyway:
    enabled: false
    locations:
      - classpath:db
    baseline-on-migrate: true
    encoding: UTF-8
    out-of-order: true
    schemas:
      - public

geoatis:
  config:
    allowed-origins-authorized: 'http://localhost:4200,http://localhost:4300'
  file-system-path: '/Users/josestadler/Documents/Geo-Satis/profile-photos'