spring:
  mvc:
    format:
      date: iso
      time: iso
      date-time: iso
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate.hbm2ddl-auto: update
      hibernate.connection.charSet: UTF-8
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/geosatis_schedule
    username: postgres
    password: postgres
  flyway:
    enabled: false
    locations:
      - classpath:flyway
    baseline-on-migrate: true
    encoding: UTF-8
    out-of-order: true
    schemas:
      - flyway